a=int(input("Enter value of a:"))
b=int(input("enter value of b:"))
print("#"*60)
print("\t{}>{}={}".format(a,b,a>b))
print("\t{}>{}={}".format(b,a,b>a))
print("\t{}<{}={}".format(a,b,a<b))
print("\t{}<{}={}".format(b,a,b<a))
print("\t{}=={}={}".format(a,b,a==b))
print("\t{}!={}={}".format(a,b,a!=b))
print("\t{}<={}={}".format(a,b,a<=b))
print("\t{}>={}={}".format(a,b,a>=b))
print("#"*60)